name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  wheel-build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - name: Install build dependencies
        run: pip install -U twine build

      - name: Build
        run: python -mbuild --wheel --sdist .

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz

      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.OPENQASM_BOT_PYPI_TOKEN }}
        run: twine upload dist/*.whl dist/*.tar.gz
